# 1 anchor, 1 aug anchor, 2 other real, 2 aug real, 3 vocoded, 3 aug vocoded
model:
  name: wav2vec2_linear_nll
  flag_fix_ssl: false
  contra_mode: 'all' # 'one' or 'all'
  loss_type: 1 # 1: 2loss, 2: loss emb only, 3: loss final hidden state only, 4: LCE only, 5: Lsupcon only
data:
  name: 'asvspoof_2019_aug_2'
  kwargs:
    vocoders: ['hifigan', 'hn-sinc-nsf-hifi', 'waveglow']
    augmentation_methods: ["RawBoost12"]
    num_additional_real: 2
    trim_length: 64000
    wav_samp_rate: 16000
    online_aug: true
    aug_dir: '/datab/phucdt/Asvspoof_aug/asvspoof2019' # path to augmented data (temp data for online augmentation, stored dir for offline augmentation)
    noise_path: '/dataa/phucdt/vocodetect/Supcon-voco/datautils/audio_augmentor/musan' # path to noise data
    rir_path: '/dataa/phucdt/vocodetect/Supcon-voco/datautils/audio_augmentor/RIRS_NOISES' # path to rir data