model:
  name: wav2vec2_linear_nll
  flag_fix_ssl: false
  contra_mode: 'all' # 'one' or 'all'
  loss_type: 1 # 1: 2loss, 2: loss emb only, 3: loss final hidden state only
  resnet:
    num_nodes: 3
    enc_dim: 256
    resnet_type: '18'
    nclasses: 2
data:
  name: 'asvspoof_2019_augall_5'
  kwargs:
    vocoders: ['hifigan', 'hn-sinc-nsf-hifi', 'waveglow']
    augmentation_methods: ["RawBoost12", "background_noise_wrapper", "reverb_wrapper", "speed_wrapper", "pitch_wrapper"]
    num_additional_real: 1
    num_additional_spoof: 1
    trim_length: 64000
    wav_samp_rate: 16000
    online_aug: true
    aug_dir: '/datab/phucdt/Asvspoof_aug/asvspoof2019'
    noise_path: '/dataa/phucdt/vocodetect/Supcon-voco/datautils/audio_augmentor/musan'
    rir_path: '/dataa/phucdt/vocodetect/Supcon-voco/datautils/audio_augmentor/RIRS_NOISES'