model:
  name: wav2vec2_btse
  flag_fix_ssl: false
  contra_mode: 'all' # 'one' or 'all'
  loss_type: 1 # 1: 2loss, 2: loss emb only, 3: loss final hidden state only
  bio_out: 64
  nb_classes: 2
  is_add: false
  bio_hid: 256
  n_heads: 4
  pf_dim: 128
  n_layers: 3
  n_bios: 3
  bio_dim: 32

data:
  name: 'asvspoof_2019_augall_5'
  kwargs:
    vocoders: ['hifigan', 'hn-sinc-nsf-hifi', 'waveglow']
    augmentation_methods: ["RawBoost12", "background_noise_wrapper", "reverb_wrapper", "speed_wrapper", "pitch_wrapper"]
    num_additional_real: 1
    num_additional_spoof: 1
    trim_length: 64000
    wav_samp_rate: 16000
    online_aug: true
    aug_dir: '/tmp/asvspoof2019' # path to augmented data (temp data for online augmentation, stored dir for offline augmentation)
    noise_path: '/tmp/musan' # path to noise data
    rir_path: '/tmp/RIRS_NOISES' # path to rir data