__title__ = "audio_augmentor"
__description__ = "Audio Augmentor for human speech data"
__url__ = ""
__version__ = "0.3.0"
__author__ = "Thien-Phuc Doan"
__author_email__ = "josebeo2016@gmail.com"
__license__ = "MIT"